doc: change Russian readme extension to `.md`
bol-van/zapret pull request #217
Opened 2024-08-04 23:54 UTC by UnkwUsr

I see English readme already uses `.md` extension, which makes nice style drawing on github site. While Russian readme still uses `.txt` extension

2024-08-05 01:28 UTC, UnkwUsr commented
Задача оказалась сложнее чем я думал. Дело в том, что в markdown параграфом считается блок текст не разделённый пустой строкой. Просмотрел весь файл 2 раза, исправил всё что нашёл.

2024-08-05 03:51 UTC, bol-van commented
там надо все проходить от и до
это работа не на раз два

2024-08-22 18:43 UTC, Hi-Angel requested changes
О, лайк, я как раз хотел тоже заняться конвертацией в markdown, хорошо что в PR'ы заглянул) Я правда думал сначала создать issue чтобы убедиться что мэйнтейнер согласен, но он согласен)

2024-08-22 18:43 UTC, Hi-Angel commented on docs/readme.md
>  Существует и более продвинутая магия, направленная на преодоление DPI на пакетном уровне.
Этот коммит явно должен быть частью предыдущего, потому что в предыдущем получается сломанный markdown документ.

2024-08-22 18:43 UTC, Hi-Angel commented on docs/readme.md
Этот коммит аналогично.

2024-10-28 06:33 UTC, closed without merging